<?php
namespace transit_realtime\TranslatedString;

// @@protoc_insertion_point(namespace:.transit_realtime.TranslatedString.Translation)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: gtfs-realtime.proto
 *
 * -*- magic methods -*-
 *
 * @method string getText()
 * @method void setText(\string $value)
 * @method string getLanguage()
 * @method void setLanguage(\string $value)
 */
class Translation extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.transit_realtime.TranslatedString.Translation)
  
  /**
   * A UTF-8 string containing the message.
   *
   * @var string $text
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $text;
  
  /**
   * BCP-47 language code. Can be omitted if the language is unknown or if
   * no i18n is done at all for the feed. At most one translation is
   * allowed to have an unspecified language tag.
   *
   * @var string $language
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $language;
  
  
  // @@protoc_insertion_point(properties_scope:.transit_realtime.TranslatedString.Translation)

  // @@protoc_insertion_point(class_scope:.transit_realtime.TranslatedString.Translation)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "text",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "language",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.transit_realtime.TranslatedString.Translation)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
