<?php
namespace transit_realtime;

// @@protoc_insertion_point(namespace:.transit_realtime.FeedHeader)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: gtfs-realtime.proto
 *
 * Metadata about a feed, included in feed messages.
 *
 * -*- magic methods -*-
 *
 * @method string getGtfsRealtimeVersion()
 * @method void setGtfsRealtimeVersion(\string $value)
 * @method \transit_realtime\FeedHeader\Incrementality getIncrementality()
 * @method void setIncrementality(\transit_realtime\FeedHeader\Incrementality $value)
 * @method string getTimestamp()
 * @method void setTimestamp(\string $value)
 */
class FeedHeader extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.transit_realtime.FeedHeader)
  
  /**
   * Version of the feed specification.
   * The current version is 1.0.
   *
   * @var string $gtfs_realtime_version
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $gtfs_realtime_version;
  
  /**
   * @var \transit_realtime\FeedHeader\Incrementality $incrementality
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_ENUM
   * @see \transit_realtime\FeedHeader\Incrementality
   **/
  protected $incrementality;
  
  /**
   * This timestamp identifies the moment when the content of this feed has been
   * created (in server time). In POSIX time (i.e., number of seconds since
   * January 1st 1970 00:00:00 UTC).
   *
   * @var string $timestamp
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_UINT64
   **/
  protected $timestamp;
  
  
  // @@protoc_insertion_point(properties_scope:.transit_realtime.FeedHeader)

  // @@protoc_insertion_point(class_scope:.transit_realtime.FeedHeader)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "gtfs_realtime_version",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_ENUM,
        "name"     => "incrementality",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => \transit_realtime\FeedHeader\Incrementality::FULL_DATASET,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_UINT64,
        "name"     => "timestamp",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.transit_realtime.FeedHeader)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
