<?php
namespace transit_realtime;

// @@protoc_insertion_point(namespace:.transit_realtime.TranslatedString)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: gtfs-realtime.proto
 *
 * An internationalized message containing per-language versions of a snippet of
 * text or a URL.
 * One of the strings from a message will be picked up. The resolution proceeds
 * as follows:
 * 1. If the UI language matches the language code of a translation,
 *    the first matching translation is picked.
 * 2. If a default UI language (e.g., English) matches the language code of a
 *    translation, the first matching translation is picked.
 * 3. If some translation has an unspecified language code, that translation is
 *    picked.
 *
 * -*- magic methods -*-
 *
 * @method array getTranslation()
 * @method void appendTranslation(\transit_realtime\TranslatedString\Translation $value)
 */
class TranslatedString extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.transit_realtime.TranslatedString)
  
  /**
   * At least one translation must be provided.
   *
   * @var array $translation
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \transit_realtime\TranslatedString\Translation
   **/
  protected $translation;
  
  
  // @@protoc_insertion_point(properties_scope:.transit_realtime.TranslatedString)

  // @@protoc_insertion_point(class_scope:.transit_realtime.TranslatedString)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "translation",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\transit_realtime\TranslatedString\Translation',
      )));
      // @@protoc_insertion_point(builder_scope:.transit_realtime.TranslatedString)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
