<?php
namespace transit_realtime\VehiclePosition;

// @@protoc_insertion_point(namespace:.transit_realtime.VehiclePosition.CongestionLevel)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: gtfs-realtime.proto
 *
 */
class CongestionLevel extends \ProtocolBuffers\Enum
{
  // @@protoc_insertion_point(traits:.transit_realtime.VehiclePosition.CongestionLevel)
  
  const UNKNOWN_CONGESTION_LEVEL = 0;
  const RUNNING_SMOOTHLY = 1;
  const STOP_AND_GO = 2;
  const CONGESTION = 3;
  const SEVERE_CONGESTION = 4;
  
  // @@protoc_insertion_point(const_scope:.transit_realtime.VehiclePosition.CongestionLevel)
  
  // @@protoc_insertion_point(class_scope:.transit_realtime.VehiclePosition.CongestionLevel)
  
  /**
   * @return \ProtocolBuffers\EnumDescriptor
   */
  public static function getEnumDescriptor()
  {
    static $descriptor;
    if (!$descriptor) {
      $builder = new \ProtocolBuffers\EnumDescriptorBuilder();
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::UNKNOWN_CONGESTION_LEVEL,
        "name"  => 'UNKNOWN_CONGESTION_LEVEL',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::RUNNING_SMOOTHLY,
        "name"  => 'RUNNING_SMOOTHLY',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::STOP_AND_GO,
        "name"  => 'STOP_AND_GO',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::CONGESTION,
        "name"  => 'CONGESTION',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::SEVERE_CONGESTION,
        "name"  => 'SEVERE_CONGESTION',
      )));
      // @@protoc_insertion_point(builder_scope:.transit_realtime.VehiclePosition.CongestionLevel)
      $descriptor = $builder->build();
    }
    return $descriptor;
  }
}
