<?php
namespace transit_realtime\VehiclePosition;

// @@protoc_insertion_point(namespace:.transit_realtime.VehiclePosition.VehicleStopStatus)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: gtfs-realtime.proto
 *
 */
class VehicleStopStatus extends \ProtocolBuffers\Enum
{
  // @@protoc_insertion_point(traits:.transit_realtime.VehiclePosition.VehicleStopStatus)
  
  /**
   * The vehicle is just about to arrive at the stop (on a stop
   * display, the vehicle symbol typically flashes).
   */
  const INCOMING_AT = 0;
  /**
   * The vehicle is standing at the stop.
   */
  const STOPPED_AT = 1;
  /**
   * The vehicle has departed and is in transit to the next stop.
   */
  const IN_TRANSIT_TO = 2;
  
  // @@protoc_insertion_point(const_scope:.transit_realtime.VehiclePosition.VehicleStopStatus)
  
  // @@protoc_insertion_point(class_scope:.transit_realtime.VehiclePosition.VehicleStopStatus)
  
  /**
   * @return \ProtocolBuffers\EnumDescriptor
   */
  public static function getEnumDescriptor()
  {
    static $descriptor;
    if (!$descriptor) {
      $builder = new \ProtocolBuffers\EnumDescriptorBuilder();
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::INCOMING_AT,
        "name"  => 'INCOMING_AT',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::STOPPED_AT,
        "name"  => 'STOPPED_AT',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::IN_TRANSIT_TO,
        "name"  => 'IN_TRANSIT_TO',
      )));
      // @@protoc_insertion_point(builder_scope:.transit_realtime.VehiclePosition.VehicleStopStatus)
      $descriptor = $builder->build();
    }
    return $descriptor;
  }
}
