<?php
namespace transit_realtime\Alert;

// @@protoc_insertion_point(namespace:.transit_realtime.Alert.Cause)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: gtfs-realtime.proto
 *
 */
class Cause extends \ProtocolBuffers\Enum
{
  // @@protoc_insertion_point(traits:.transit_realtime.Alert.Cause)
  
  const UNKNOWN_CAUSE = 1;
  const OTHER_CAUSE = 2;
  const TECHNICAL_PROBLEM = 3;
  const STRIKE = 4;
  const DEMONSTRATION = 5;
  const ACCIDENT = 6;
  const HOLIDAY = 7;
  const WEATHER = 8;
  const MAINTENANCE = 9;
  const CONSTRUCTION = 10;
  const POLICE_ACTIVITY = 11;
  const MEDICAL_EMERGENCY = 12;
  
  // @@protoc_insertion_point(const_scope:.transit_realtime.Alert.Cause)
  
  // @@protoc_insertion_point(class_scope:.transit_realtime.Alert.Cause)
  
  /**
   * @return \ProtocolBuffers\EnumDescriptor
   */
  public static function getEnumDescriptor()
  {
    static $descriptor;
    if (!$descriptor) {
      $builder = new \ProtocolBuffers\EnumDescriptorBuilder();
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::UNKNOWN_CAUSE,
        "name"  => 'UNKNOWN_CAUSE',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::OTHER_CAUSE,
        "name"  => 'OTHER_CAUSE',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::TECHNICAL_PROBLEM,
        "name"  => 'TECHNICAL_PROBLEM',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::STRIKE,
        "name"  => 'STRIKE',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::DEMONSTRATION,
        "name"  => 'DEMONSTRATION',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::ACCIDENT,
        "name"  => 'ACCIDENT',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::HOLIDAY,
        "name"  => 'HOLIDAY',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::WEATHER,
        "name"  => 'WEATHER',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::MAINTENANCE,
        "name"  => 'MAINTENANCE',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::CONSTRUCTION,
        "name"  => 'CONSTRUCTION',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::POLICE_ACTIVITY,
        "name"  => 'POLICE_ACTIVITY',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::MEDICAL_EMERGENCY,
        "name"  => 'MEDICAL_EMERGENCY',
      )));
      // @@protoc_insertion_point(builder_scope:.transit_realtime.Alert.Cause)
      $descriptor = $builder->build();
    }
    return $descriptor;
  }
}
