<?php
namespace transit_realtime\Alert;

// @@protoc_insertion_point(namespace:.transit_realtime.Alert.Effect)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: gtfs-realtime.proto
 *
 */
class Effect extends \ProtocolBuffers\Enum
{
  // @@protoc_insertion_point(traits:.transit_realtime.Alert.Effect)
  
  const NO_SERVICE = 1;
  const REDUCED_SERVICE = 2;
  /**
   * We don't care about INsignificant delays: they are hard to detect, have
   * little impact on the user, and would clutter the results as they are too
   * frequent.
   */
  const SIGNIFICANT_DELAYS = 3;
  const DETOUR = 4;
  const ADDITIONAL_SERVICE = 5;
  const MODIFIED_SERVICE = 6;
  const OTHER_EFFECT = 7;
  const UNKNOWN_EFFECT = 8;
  const STOP_MOVED = 9;
  
  // @@protoc_insertion_point(const_scope:.transit_realtime.Alert.Effect)
  
  // @@protoc_insertion_point(class_scope:.transit_realtime.Alert.Effect)
  
  /**
   * @return \ProtocolBuffers\EnumDescriptor
   */
  public static function getEnumDescriptor()
  {
    static $descriptor;
    if (!$descriptor) {
      $builder = new \ProtocolBuffers\EnumDescriptorBuilder();
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::NO_SERVICE,
        "name"  => 'NO_SERVICE',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::REDUCED_SERVICE,
        "name"  => 'REDUCED_SERVICE',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::SIGNIFICANT_DELAYS,
        "name"  => 'SIGNIFICANT_DELAYS',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::DETOUR,
        "name"  => 'DETOUR',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::ADDITIONAL_SERVICE,
        "name"  => 'ADDITIONAL_SERVICE',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::MODIFIED_SERVICE,
        "name"  => 'MODIFIED_SERVICE',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::OTHER_EFFECT,
        "name"  => 'OTHER_EFFECT',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::UNKNOWN_EFFECT,
        "name"  => 'UNKNOWN_EFFECT',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::STOP_MOVED,
        "name"  => 'STOP_MOVED',
      )));
      // @@protoc_insertion_point(builder_scope:.transit_realtime.Alert.Effect)
      $descriptor = $builder->build();
    }
    return $descriptor;
  }
}
